- name: Join Swarm Cluster
  hosts: tag_Name_manager
  remote_user: ec2-user
  gather_facts: False
  vars:
    token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Check if Swarm Mode in worker is already activated
      command: docker info
      register: docker_info
      changed_when: false

    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      when: "'Swarm: active' not in docker_info.stdout"
      register: worker

- name: Start docker stack
  hosts: tag_Name_manager
  become: true
  gather_facts: False
  remote_user: ec2-user
  tasks:
    - name: Copy docker folder
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user/
      changed_when: False

    - name: docker stack
      command: docker stack deploy --compose-file=docker-compose.yml tutum_stack
      changed_when: False
