---
- name: Install docker on manager and worker mashine
  hosts: tag_Environment_swarm_mashines[0]
  become: true
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  roles:
    - docker

- name: Install docker on worker mashine
  hosts: tag_Environment_swarm_mashines[1]
  become: true
  become_method: sudo
  become_user: root
  remote_user: ec2-user
  roles:
    - docker
